name: breathe_easy_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.4.0

  # HTTP Routing & Requesting
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.1.0

  # Environment Variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
